# Temporarily disabled docker
# https://www.refme.com/blog/2015/11/05/haskell-travis-heroku-and-docker-oh-my/

dist:     trusty
language: sh
sudo:     false

matrix:
  include:
    - os: linux
    - os: osx

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.24
      - ghc-7.10.3
      - alex
      - happy
      - ocaml
      - camlp5
      - nodejs

env:
  global:
    - COQVER=8.5pl1

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
    - $TRAVIS_BUILD_DIR/coq-$COQVER
    - $TRAVIS_BUILD_DIR/web/js/peacoq-ts/typings
    - $TRAVIS_BUILD_DIR/web/node_modules

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/before-install-linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];   then ./scripts/before-install-osx.sh; fi

install:
  - export PATH=/opt/cabal/1.24/bin:$PATH
  - export PATH=/opt/ghc/7.10.3/bin:$PATH
  - export PATH=$TRAVIS_BUILD_DIR/coq-$COQVER/bin:$PATH
  - cabal update
  # building src/Handlers.hs takes more than 10 minutes on Travis :(
  - travis_wait 40 ./setup.sh

script:
  - (cd peacoqtop && ./dist/build/peacoqtop-test/peacoqtop-test)
  - (cd peacoq-server && ./dist/build/peacoq-server-test/peacoq-server-test)
